version: "3.4"
# uses environment variables set in .env
# example @ ./example.env
# see readme.md for more info

volumes:
  grafana-storage:
  ackee-storage:

services:

    pgadmin:
        restart: unless-stopped
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${YX_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${YX_PG_PASS}
            - PGADMIN_ENABLE_TLS=True
        volumes:
            - ../ssl/cert.pem:/certs/server.cert
            - ../ssl/privkey.pem:/certs/server.key
        ports:
            - "${YX_PG_PORT:-7001}:443"

    grafana:
        restart: unless-stopped
        image: grafana/grafana
        volumes:
            - grafana-storage:/var/lib/grafana
            - ${YX_SSL_CERT_LOCATION}:/certs/server.cert
            - ${YX_SSL_KEY_LOCATION}:/certs/server.key
        environment:
            - GF_SERVER_PROTOCOL=https
            - GF_SERVER_ENABLE_GZIP=${YX_GF_GZIP:-true}
            - GF_SERVER_CERT_FILE=/certs/server.cert
            - GF_SERVER_CERT_KEY=/certs/server.key
        ports:
            - "${YX_GF_PORT:-7002}:3000"

    bunker_dozzle:
        image: bunkerity/bunkerized-nginx
        restart: always
        volumes:
            - ${YX_SSL_CERT_LOCATION}:/certs/server.cert
            - ${YX_SSL_KEY_LOCATION}:/certs/server.key
        environment:
            - USE_REVERSE_PROXY=yes
            - REVERSE_PROXY_URL=/
            - REVERSE_PROXY_HOST=http://dozzle:8080
            - USE_CUSTOM_HTTPS=yes
            - CUSTOM_HTTPS_CERT=/certs/server.cert
            - CUSTOM_HTTPS_KEY=/certs/server.key
            - USE_AUTH_BASIC=yes
            - USE_DNSBL=no
            - USE_FAILBAN=no
            - LIMIT_REQ=no
            - USE_CLAMAV_SCAN=no
            - USE_CLAMAV_UPLOAD=no
            - USE_MODSECURITY=no
            - USE_MODSECURITY_CRS=no
            - BLOCK_USER_AGENT=no
            - AUTH_BASIC_USER=${YX_BNK_DL_USER:-bnk_user}
            - AUTH_BASIC_PASSWORD=${YX_BNK_DL_PASS:-bnk_pass}
        ports:
            - "${YX_BNK_DL_PORT:-7003}:8443"

    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    ackee:
        image: electerious/ackee
        container_name: ackee
        restart: always
        environment:
            - WAIT_HOSTS=ackee_mongo:27017
            - ACKEE_MONGODB=mongodb://ackee_mongo:27017/ackee
            - ACKEE_USERNAME=${YX_ACKEE_USER:-ackee_user}
            - ACKEE_PASSWORD=${YX_ACKEE_PASS:-ackee_pass}
        depends_on:
          - ackee_mongo

    bunker_ackee:
        image: bunkerity/bunkerized-nginx
        restart: always
        volumes:
            - ${YX_SSL_CERT_LOCATION}:/certs/server.cert
            - ${YX_SSL_KEY_LOCATION}:/certs/server.key
        environment:
            - USE_REVERSE_PROXY=yes
            - REVERSE_PROXY_URL=/
            - REVERSE_PROXY_HOST=http://ackee:3000
            - USE_CUSTOM_HTTPS=yes
            - CUSTOM_HTTPS_CERT=/certs/server.cert
            - CUSTOM_HTTPS_KEY=/certs/server.key
            - USE_DNSBL=no
            - USE_FAILBAN=no
            - LIMIT_REQ=no
            - USE_CLAMAV_SCAN=no
            - USE_CLAMAV_UPLOAD=no
            - USE_MODSECURITY=no
            - USE_MODSECURITY_CRS=no
            - BLOCK_USER_AGENT=no
        ports:
            - "${YX_BNK_ACKEE_PORT:-7004}:8443"

    ackee_mongo:
        image: mongo
        container_name: ackee_mongo
        restart: always
        volumes:
          - ackee-storage:/data/db
