version: "3.4"
# uses environment variables set in .env
# example @ ./example.env
# see readme.md for more info

volumes:
  grafana-storage:
  ackee-storage:

services:
    pgadmin:
        restart: unless-stopped
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=yacsrpi@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=${GRAFANA_PASSWORD}
            - PGADMIN_ENABLE_TLS=True
        volumes:
            - ../ssl/cert.pem:/certs/server.cert
            - ../ssl/privkey.pem:/certs/server.key
        ports:
            - "${YX_PG_PORT:-7001}:443"
    
    ackee:
        image: electerious/ackee
        container_name: ackee
        restart: always
        environment:
            - WAIT_HOSTS=ackee_mongo:27017
            - ACKEE_MONGODB=mongodb://ackee_mongo:27017/ackee
            - ACKEE_USERNAME=${YX_ACKEE_USER:-ackee_user}
            - ACKEE_PASSWORD=${YX_ACKEE_PASS:-ackee_pass}
        depends_on:
          - ackee_mongo
    
    ackee_mongo:
        image: mongo
        container_name: ackee_mongo
        restart: always
        volumes:
          - ackee-storage:/data/db

    prometheus:
        image: prom/prometheus:latest
        user: root
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
          - ./data/prometheus/config/:/etc/prometheus/
          - ./data/prometheus/data/:/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
        expose:
          - 9090
        ports:
          - 9090:9090
        links:
          - cadvisor:cadvisor
          - node-exporter:node-exporter

    node-exporter:
        image: prom/node-exporter:latest
        container_name: monitoring_node_exporter
        restart: unless-stopped
        expose:
          - 9100

    cadvisor:
        image: google/cadvisor:latest
        container_name: monitoring_cadvisor
        restart: unless-stopped
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
          - 9999:8080

    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
          - prometheus:prometheus
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
          - GF_USERS_ALLOW_SIGN_UP=false
          - GF_SERVER_DOMAIN=yacs.cs.rpi.edu
          - GF_SMTP_ENABLED=false
        expose:
            - 4000
        ports:
          - 4000:4000