# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"
    subconfig.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.skip_tags = ["ec2"]
      ansible.verbose = true
      ansible.extra_vars = { ansible_python_interpreter: "python3" }
    end
  end

end
